/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROBOT_MESSAGES_PB_H_INCLUDED
#define PB_ROBOT_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Status_TopState {
    Status_TopState_LINE_FOLLOWING = 0,
    Status_TopState_METAL_DETECTING = 1,
    Status_TopState_TELETUBBYING = 2,
    Status_TopState_HABITATING = 3
} Status_TopState;

/* Struct definitions */
/* RPi -> ESP32: fired whenever CV confirms a new teletubby sighting. */
typedef struct _Detection {
    float bearing_deg; /* degrees from frame center; + = right of center */
    bool is_new; /* true only for a not-yet-seen hue (dedup done on RPi) */
} Detection;

/* ESP32 -> RPi: current top-level state, sent every control loop.
 RPi uses this to gate CV work (e.g. skip inference while not line_following). */
typedef struct _Status {
    Status_TopState state;
} Status;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Status_TopState_MIN Status_TopState_LINE_FOLLOWING
#define _Status_TopState_MAX Status_TopState_HABITATING
#define _Status_TopState_ARRAYSIZE ((Status_TopState)(Status_TopState_HABITATING+1))


#define Status_state_ENUMTYPE Status_TopState


/* Initializer values for message structs */
#define Detection_init_default                   {0, 0}
#define Status_init_default                      {_Status_TopState_MIN}
#define Detection_init_zero                      {0, 0}
#define Status_init_zero                         {_Status_TopState_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define Detection_bearing_deg_tag                1
#define Detection_is_new_tag                     2
#define Status_state_tag                         1

/* Struct field encoding specification for nanopb */
#define Detection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    bearing_deg,       1) \
X(a, STATIC,   SINGULAR, BOOL,     is_new,            2)
#define Detection_CALLBACK NULL
#define Detection_DEFAULT NULL

#define Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define Status_CALLBACK NULL
#define Status_DEFAULT NULL

extern const pb_msgdesc_t Detection_msg;
extern const pb_msgdesc_t Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Detection_fields &Detection_msg
#define Status_fields &Status_msg

/* Maximum encoded size of messages (where known) */
#define Detection_size                           7
#define ROBOT_MESSAGES_PB_H_MAX_SIZE             Detection_size
#define Status_size                              2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
