/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROBOT_MESSAGES_PB_H_INCLUDED
#define PB_ROBOT_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Command {
    bool teletubby_detected;
} Command;

typedef struct _SensorState {
    bool state_completed;
    bool metal_detected;
} SensorState;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Command_init_default                     {0}
#define SensorState_init_default                 {0, 0}
#define Command_init_zero                        {0}
#define SensorState_init_zero                    {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Command_teletubby_detected_tag           1
#define SensorState_state_completed_tag          1
#define SensorState_metal_detected_tag           2

/* Struct field encoding specification for nanopb */
#define Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     teletubby_detected,   1)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL

#define SensorState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     state_completed,   1) \
X(a, STATIC,   SINGULAR, BOOL,     metal_detected,    2)
#define SensorState_CALLBACK NULL
#define SensorState_DEFAULT NULL

extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t SensorState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Command_fields &Command_msg
#define SensorState_fields &SensorState_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             2
#define ROBOT_MESSAGES_PB_H_MAX_SIZE             SensorState_size
#define SensorState_size                         4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
